name: TestingLeo
favicon: null
layout_spectrum: 0.7212042149621993
typography_spectrum: 0.49010466900654137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7444113581441343
  lightness: 0.5582984525244683
  saturation: 0.8146756268106401
  rhythmicContrast: 0.5611547462176532
purpose: []
